version: '3.6'

services:
  frontend:
    image: "rubykube/mikroapp:0.1.5"
    volumes:
      - ../config/frontend/env.js:/home/node/public/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:trade.bitas.net"
      traefik.port: 3000

  tower:
    image: "rubykube/tower:0.1.8"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:trade.bitas.net"
      traefik.port: 8080

